#!/usr/bin/env python3
"""Generate crates/ephemeris/src/tables.rs from the verified coefficient lists.

Source of coefficients:
  Moon : ELP2000-82B truncated as published in Meeus, ch.47 table 47.A
         (units 1e-6 deg).

太阳的 VSOP87D 表**不在这里**——它由 tools/gen_vsop87.py 从 VSOP87D 原始系数
文件生成到 vsop87_tables.rs。之前这里是 Meeus 附录 III 的转抄版，实测在
J2000 处就有 −0.24" 的系统差，已弃用。

Run:  python tools/gen_tables.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, os.pardir, 'probe'))

import moon_test as M   # noqa: E402

OUT = os.path.join(HERE, os.pardir, 'crates', 'ephemeris', 'src', 'tables.rs')


def vsop(name, terms):
    lines = [f'pub(crate) static {name}: &[(f64, f64, f64)] = &[']
    for a, b, c in terms:
        lines.append(f'    ({a!r}, {b!r}, {c!r}),')
    lines.append('];')
    return '\n'.join(lines)


def moon_lon(name, terms):
    lines = [f'pub(crate) static {name}: &[(i8, i8, i8, i8, i32, i32)] = &[']
    for d, m, mp, f, l, r in terms:
        lines.append(f'    ({d}, {m}, {mp}, {f}, {l}, {r}),')
    lines.append('];')
    return '\n'.join(lines)


def moon_lat(name, terms):
    lines = [f'pub(crate) static {name}: &[(i8, i8, i8, i8, i32)] = &[']
    for d, m, mp, f, b in terms:
        lines.append(f'    ({d}, {m}, {mp}, {f}, {b}),')
    lines.append('];')
    return '\n'.join(lines)


HEADER = '''// @generated by tools/gen_tables.py -- do not edit by hand.
//
// 月亮: ELP2000-82B 截断级数 (Meeus 第 47 章 表 47.A / 47.B)。
//       表 47.A 的经度系数单位 1e-6 度, 距离系数单位 1e-3 km;
//       表 47.B 的纬度系数单位 1e-6 度。
'''

parts = [HEADER]
parts.append(moon_lon('MOON_LON', M.TA))
parts.append(moon_lat('MOON_LAT', M.TB))

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n\n'.join(parts) + '\n')
print('wrote', OUT)
