#!/usr/bin/env python3
"""Generate crates/ephemeris/src/nutation_tables.rs from ERFA's nut00a.c.

IAU 2000A 章动模型：678 条日月项 + 687 条行星项。本仓库原先只用 4 项缩写式
（误差 0.34″）；转录这张权威表后可以降到 0.001″ 量级。

系数单位是 **0.1 微角秒**（ERFA 里 `U2R = DAS2R / 1e7`），所以别改单位。

Run:  python tools/gen_nutation.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, os.pardir, 'third_party', 'erfa', 'nut00a.c')
OUT = os.path.join(HERE, os.pardir, 'crates', 'ephemeris', 'src', 'nutation_tables.rs')


def parse_block(text, name):
    """取 `name[] = { ... };` 里的记录。

    **一条记录可能跨多行**（C 源码里前几十条就是两行），所以不能按行切，
    要按 `}` 切。先去掉注释，再按 `},` 分块。
    """
    i = text.index(f'{name}[] = {{')
    j = text.index('};', i)
    body = re.sub(r'/\*.*?\*/', ' ', text[i:j], flags=re.S)
    body = body[body.index('{') + 1:]
    rows = []
    for chunk in body.split('},'):
        nums = re.findall(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?', chunk)
        if nums:
            rows.append([float(x) for x in nums])
    return rows


def main():
    text = open(SRC, encoding='utf-8').read()
    ls = parse_block(text, 'xls')
    pl = parse_block(text, 'xpl')
    print(f'日月项 {len(ls)}，行星项 {len(pl)}')

    # 日月项：{nl,nlp,nf,nd,nom, sp,spt,cp, ce,cet,se}  -> 11 个数
    bad = [r for r in ls if len(r) != 11]
    assert not bad, f'日月项列数不对：{bad[:2]}'
    bad = [r for r in pl if len(r) != 17]
    assert not bad, f'行星项列数不对：{bad[:2]}'

    L = []
    L.append('// @generated by tools/gen_nutation.py -- do not edit by hand.')
    L.append('//')
    L.append('// IAU 2000A 章动模型（MHB2000）。系数来源于 ERFA 的 src/nut00a.c，')
    L.append('// 见 third_party/erfa/README.md。')
    L.append('//')
    L.append('// 系数单位 **0.1 微角秒**——ERFA 里是 `U2R = DAS2R / 1e7`，换算见 nutation.rs。')
    L.append('')
    L.append('/// 日月章动一项：`(nl, nlp, nf, nd, nom, sp, spt, cp, ce, cet, se)`。')
    L.append('///')
    L.append("/// 引数为 `nl*l + nlp*l' + nf*F + nd*D + nom*Om`。")
    L.append('///')
    L.append('/// 对黄经的贡献是 `(sp + spt*t)*sin + cp*cos`，')
    L.append('/// 对交角的贡献是 `(ce + cet*t)*cos + se*sin`。')
    L.append('///')
    L.append('/// 这里用元组而非结构体是**有意的**：这是生成的数据表，1365 行每行都写字段名')
    L.append('/// 会把文件撑大十倍，而唯一的消费处是一句解构——名字就在那里。')
    L.append('pub type NutLsTerm = (i8, i8, i8, i8, i8, f64, f64, f64, f64, f64, f64);')
    L.append('')
    L.append('pub static NUT_LS: &[NutLsTerm] = &[')
    for r in ls:
        L.append('    ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}),'.format(
            *(int(x) for x in r[:5]), *(repr(x) for x in r[5:])))
    L.append('];')
    L.append('')
    L.append('/// 行星章动一项：`(nl, nf, nd, nom, nme, nve, nea, nma, nju, nsa, nur, nne,')
    L.append('/// npa, sp, cp, ce, se)`——前 13 个是引数乘子，后 4 个是系数。')
    L.append('pub type NutPlTerm = (i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, f64, f64, f64, f64);')
    L.append('')
    L.append('pub static NUT_PL: &[NutPlTerm] = &[')
    for r in pl:
        L.append('    ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}),'.format(
            *(int(x) for x in r[:13]), *(repr(x) for x in r[13:])))
    L.append('];')
    L.append('')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(L))
    print('wrote', OUT, os.path.getsize(OUT), 'bytes')
    return 0


if __name__ == '__main__':
    sys.exit(main())
