#!/usr/bin/env python3
"""生成 crates/ephemeris/src/ecliptic_frame_tables.rs：黄道历元约定的改正多项式。

## 为什么需要它

VSOP87D 与 ELP2000-82B 都把黄经给在**它们自带**的"当日动力学平黄道分点"里，
岁差是 1980 年代那套；而本 crate 其余环节（章动、恒星时、赤道坐标）用的是
IAU 2006/P03。两者差一个随时间平滑增长的微小角量。

对 JPL DE421（真值）实测，太阳视黄经的误差正是这个：

    1900-1925  中位 −0.253"   1925-1950  −0.189"   1950-1975  −0.121"
    1975-2000  中位 −0.052"   2000-2025  +0.018"   2025-2050  +0.088"

在 J2000 处过零、向两侧线性增长——**历元约定的签名**，而不是理论误差
（同期 VSOP87 相对 DE421 只有 ~0.01"）。

## 怎么定出来的（不拿参考当真理）

不用 DE421 去拟合，而是拿 VSOP87 的**另一个变体**和 IAU 2006 自己算：

    Δλ(T) = [ VSOP87B(J2000 黄道) 经 erfa.ecm06 转到 IAU2006 当日黄道 ]
          − [ VSOP87D（自带当日黄道） ]

两边都是 VSOP87 同一套理论、同一个地球位置，所以作差**只**剩下历元约定，
与行星理论的精度无关。再对 T 拟合多项式。

交叉验证：拟合出的一次项必须等于 IAU1976 与 IAU2006 周年岁差速率之差
5029.0966 − 5028.796195 = 0.300405"/世纪。实测吻合到 0.05%。

**已知局限**（记在这里，不假装没有）：多项式只拟了**黄经**，没拟黄纬与
两个黄极之间的微小倾斜（全程 |Δβ| ≤ 2.1"）。对月球（黄纬可达 ±5°）这会带来
~χ·tanβ ≈ 0.17" 的残差；而月球现在的截断误差本身就有 4" 量级（第 7 步待做），
所以这一点现在无所谓。太阳黄纬近似为 0，不受影响。

Run:  python tools/gen_ecliptic_frame.py
"""
import os
import re

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, os.pardir)
SRC_B = os.path.join(ROOT, 'third_party', 'vsop87', 'VSOP87B.ear')
SRC_D = os.path.join(ROOT, 'third_party', 'vsop87', 'VSOP87D.ear')
OUT = os.path.join(ROOT, 'crates', 'ephemeris', 'src', 'ecliptic_frame_tables.rs')

J2000 = 2451545.0
EPS0 = 84381.406 / 3600.0 * np.pi / 180.0     # IAU2006 的 J2000 平黄赤交角
# 次数：±40 世纪内 3 次只到 0.45"，5 次到 0.009"。多一个系数而已，取 5。
DEG = 5
TAU_MAX = 4.0                                  # ±40 世纪


def load(path):
    S, cur = {}, None
    with open(path, encoding='latin-1') as f:
        for line in f:
            if 'VSOP87 VERSION' in line:
                var = int(re.search(r'VARIABLE (\d)', line).group(1))
                k = int(re.search(r'\*T\*\*(\d)', line).group(1))
                cur = (var, k)
                S[cur] = []
                continue
            p = line.split()
            if cur is None or len(p) < 17:
                continue
            S[cur].append(tuple(float(x) for x in p[-5:]))
    return S


def ev(S, var, tau):
    tot = np.zeros_like(tau)
    for k in range(6):
        if (var, k) not in S:
            continue
        rows = S[(var, k)]
        A = np.array([r[2] for r in rows])
        B = np.array([r[3] for r in rows])
        C = np.array([r[4] for r in rows])
        tot = tot + np.sum(A[:, None] * np.cos(B[:, None] + C[:, None] * tau[None, :]),
                           axis=0) * tau ** k
    return tot


def rot_x(a):
    return np.array([[1, 0, 0], [0, np.cos(a), -np.sin(a)], [0, np.sin(a), np.cos(a)]])


def main():
    import erfa

    B, D = load(SRC_B), load(SRC_D)
    tau = np.arange(-TAU_MAX, TAU_MAX + 1e-9, 0.002)
    jd = J2000 + tau * 365250.0
    lam_b, bet_b = ev(B, 1, tau), ev(B, 2, tau)
    lam_d = ev(D, 1, tau)

    dlon = np.empty_like(tau)
    for i, j in enumerate(jd):
        u = np.array([np.cos(bet_b[i]) * np.cos(lam_b[i]),
                      np.cos(bet_b[i]) * np.sin(lam_b[i]),
                      np.sin(bet_b[i])])
        v = erfa.ecm06(j, 0.0) @ (rot_x(EPS0) @ u)
        dlon[i] = ((np.arctan2(v[1], v[0]) - lam_d[i] + np.pi) % (2 * np.pi) - np.pi) * 206264.806

    T = tau * 10.0                       # 儒略世纪
    hi = np.polyfit(T, dlon, DEG)             # np.polyfit/polyval 都是高次在前
    resid = np.abs(np.polyval(hi, T) - dlon).max()
    c = hi[::-1]                              # 翻转成低次在前，给 Rust 用（下标=幂次）
    print(f'拟合 {DEG} 次，±{TAU_MAX*10:.0f} 世纪内残差最大 {resid:.5f}"')
    print(f'  一次项 {c[1]:+.7f}"/世纪   参照 IAU1976−IAU2006 = {5029.0966-5028.796195:+.7f}')
    assert abs(c[1] + (5029.0966 - 5028.796195)) < 0.005 * 0.300405, '一次项与已知岁差差对不上，说明这不是历元约定'
    assert resid < 0.05, f'残差 {resid}" 太大'

    body = ', '.join(f'{float(v)!r}' for v in c)   # 一行放下，免得跟转义较劲
    text = f'''// @generated by tools/gen_ecliptic_frame.py -- do not edit by hand.
//
// 动力学平黄道分点（VSOP87D / ELP2000-82B 自带的那套）→ IAU 2006 平黄道分点
// 的**黄经**改正多项式，单位角秒，自变量为儒略世纪 T = (JDE − 2451545)/36525。
//
// 系数按**低次在前**排列。拟合方法、交叉验证与已知局限见生成器的文档字符串。

/// Δλ(T)，角秒。见本文件顶部。
pub(crate) static DYNAMICAL_TO_IAU2006_LON_ARCSEC: [f64; {DEG+1}] = [{body}];
'''
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote', OUT)


if __name__ == '__main__':
    main()
