#!/usr/bin/env python3
"""Generate crates/ephemeris/src/nutation_tables.rs from ERFA's nut00a.c.

IAU 2000A 章动模型：678 条日月项 + 687 条行星项。本仓库原先只用 4 项缩写式
（误差 0.34″）；转录这张权威表后可以降到 0.001″ 量级。

系数单位是 **0.1 微角秒**（ERFA 里 `U2R = DAS2R / 1e7`），所以别改单位。

Run:  python tools/gen_nutation.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, os.pardir, 'third_party', 'erfa', 'nut00a.c')
OUT = os.path.join(HERE, os.pardir, 'crates', 'ephemeris', 'src', 'nutation_tables.rs')


def parse_block(text, name):
    """取 `name[] = { ... };` 里的记录。

    **一条记录可能跨多行**（C 源码里前几十条就是两行），所以不能按行切，
    要按 `}` 切。先去掉注释，再按 `},` 分块。
    """
    i = text.index(f'{name}[] = {{')
    j = text.index('};', i)
    body = re.sub(r'/\*.*?\*/', ' ', text[i:j], flags=re.S)
    body = body[body.index('{') + 1:]
    rows = []
    for chunk in body.split('},'):
        nums = re.findall(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?', chunk)
        if nums:
            rows.append([float(x) for x in nums])
    return rows


# 系数全部小于此值（单位 0.1 微角秒）的项丢弃。
#
# 这不是偷工：1365 项里绝大多数远低于本 crate 的目标精度。按最坏情况（被丢的项
# 全部同相相加）估计，阈值 100（= 1e-5 角秒）丢掉的总幅度 ≤ 0.0019″，
# 而判据是 0.01″。换来的是项数 1365 -> 284，章动从 54 µs 降到约 11 µs。
# 实测误差见 tools/framecheck.py。
MIN_COEFF = 100.0

# 上面的界是 t 无关的，**前提**是被丢的项不带时间因子。
#
# 日月项有 spt / cet 两列是 t·sin / t·cos，一个被丢的 |spt| = 90 的项在 t = 40 世纪
# 会贡献 90×40 = 3600 单位（3.6e-4″）。所以"幅度求和"这个界只有在被丢项的
# spt、cet 全为 0 时才成立。实测确实全为 0（带 t 因子的项系数都大，都被留下了），
# 下面的 assert 把这个巧合变成必须成立的条件——换表时若不再成立会立刻炸。
LS_COL_SP, LS_COL_SPT, LS_COL_CP = 5, 6, 7
PL_COL_FIRST = 13   # 行星项 {0..12 乘子, sp,cp,se,ce}，没有 t 列


def main():
    text = open(SRC, encoding='utf-8').read()
    all_ls = parse_block(text, 'xls')
    all_pl = parse_block(text, 'xpl')
    ls = [r for r in all_ls if max(abs(x) for x in r[LS_COL_SP:]) >= MIN_COEFF]
    pl = [r for r in all_pl if max(abs(x) for x in r[PL_COL_FIRST:]) >= MIN_COEFF]

    dropped_ls = [r for r in all_ls if r not in ls]
    bad = [r for r in dropped_ls if r[LS_COL_SPT] or r[9]]
    assert not bad, f'被剪掉的日月项带 t 因子，最坏界不再是 t 无关：{bad[:2]}'
    print(f'日月项 {len(ls)}（阈值 {MIN_COEFF}），行星项 {len(pl)}；'
          f'剪掉的 {len(dropped_ls)} 项 t 因子全为 0，界与 t 无关')

    # 日月项：{nl,nlp,nf,nd,nom, sp,spt,cp, ce,cet,se}  -> 11 个数
    bad = [r for r in ls + dropped_ls if len(r) != 11]
    assert not bad, f'日月项列数不对：{bad[:2]}'
    bad = [r for r in pl if len(r) != 17]
    assert not bad, f'行星项列数不对：{bad[:2]}'

    L = []
    L.append('// @generated by tools/gen_nutation.py -- do not edit by hand.')
    L.append('//')
    L.append('// IAU 2000A 章动模型（MHB2000）。系数来源于 ERFA 的 src/nut00a.c，')
    L.append('// 见 third_party/erfa/README.md。')
    L.append('//')
    L.append('// 系数单位 **0.1 微角秒**——ERFA 里是 `U2R = DAS2R / 1e7`，换算见 nutation.rs。')
    L.append('')
    L.append('/// 日月章动一项：`(nl, nlp, nf, nd, nom, sp, spt, cp, ce, cet, se)`。')
    L.append('///')
    L.append("/// 引数为 `nl*l + nlp*l' + nf*F + nd*D + nom*Om`。")
    L.append('///')
    L.append('/// 对黄经的贡献是 `(sp + spt*t)*sin + cp*cos`，')
    L.append('/// 对交角的贡献是 `(ce + cet*t)*cos + se*sin`。')
    L.append('///')
    L.append('/// 这里用元组而非结构体是**有意的**：这是生成的数据表，1365 行每行都写字段名')
    L.append('/// 会把文件撑大十倍，而唯一的消费处是一句解构——名字就在那里。')
    L.append('pub type NutLsTerm = (i8, i8, i8, i8, i8, f64, f64, f64, f64, f64, f64);')
    L.append('')
    L.append('pub static NUT_LS: &[NutLsTerm] = &[')
    for r in ls:
        L.append('    ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}),'.format(
            *(int(x) for x in r[:5]), *(repr(x) for x in r[5:])))
    L.append('];')
    L.append('')
    L.append('/// 行星章动一项：`(nl, nf, nd, nom, nme, nve, nea, nma, nju, nsa, nur, nne,')
    L.append('/// npa, sp, cp, ce, se)`——前 13 个是引数乘子，后 4 个是系数。')
    L.append('pub type NutPlTerm = (i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, f64, f64, f64, f64);')
    L.append('')
    L.append('pub static NUT_PL: &[NutPlTerm] = &[')
    for r in pl:
        L.append('    ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}),'.format(
            *(int(x) for x in r[:13]), *(repr(x) for x in r[13:])))
    L.append('];')
    L.append('')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(L))
    print('wrote', OUT, os.path.getsize(OUT), 'bytes')
    return 0


if __name__ == '__main__':
    sys.exit(main())
