#!/usr/bin/env python3
"""Generate crates/ephemeris/src/tables.rs from the verified coefficient lists.

Source of coefficients:
  Sun  : VSOP87D Earth, truncated as published in Meeus, "Astronomical
         Algorithms" 2nd ed., Appendix III (units 1e-8 rad / 1e-8 AU).
  Moon : ELP2000-82B truncated as published in Meeus, ch.47 table 47.A
         (units 1e-6 deg).

Both were checked against the published worked examples; see probe/.

Run:  python tools/gen_tables.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, os.pardir, 'probe'))

import vsop_test as V   # noqa: E402
import moon_test as M   # noqa: E402

OUT = os.path.join(HERE, os.pardir, 'crates', 'ephemeris', 'src', 'tables.rs')


def vsop(name, terms):
    lines = [f'pub static {name}: &[(f64, f64, f64)] = &[']
    for a, b, c in terms:
        lines.append(f'    ({a!r}, {b!r}, {c!r}),')
    lines.append('];')
    return '\n'.join(lines)


def moon_lon(name, terms):
    lines = [f'pub static {name}: &[(i8, i8, i8, i8, i32, i32)] = &[']
    for d, m, mp, f, l, r in terms:
        lines.append(f'    ({d}, {m}, {mp}, {f}, {l}, {r}),')
    lines.append('];')
    return '\n'.join(lines)


HEADER = '''// @generated by tools/gen_tables.py -- do not edit by hand.
//
// 太阳: VSOP87D 地球级数 (Meeus《Astronomical Algorithms》2nd ed. 附录 III)。
//       单位 1e-8 rad; 每一项 A*cos(B + C*tau), tau 为儒略千年数。
// 月亮: ELP2000-82B 截断级数 (Meeus 第 47 章表 47.A)。
//       经度系数单位 1e-6 度, 距离系数单位 1e-3 km。
'''

parts = [HEADER]
for n in ['L0', 'L1', 'L2', 'L3', 'L4', 'L5', 'B0', 'B1', 'R0', 'R1', 'R2', 'R3', 'R4']:
    parts.append(vsop('EARTH_' + n, getattr(V, n)))
parts.append(moon_lon('MOON_LON', M.TA))

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n\n'.join(parts) + '\n')
print('wrote', OUT)
