#!/usr/bin/env python3
"""从 VSOP87D 原始系数文件生成 crates/ephemeris/src/vsop87_tables.rs。

来源是 `third_party/vsop87/VSOP87D.ear`（VSOP87 官方文件，CDS VI/81），
不是 Meeus 附录 III 的转抄版。这一点很要紧：Meeus 那份只留了 64/559 个
L0 项、且系数经过重排，实测比"按振幅留同样多项"差一倍，在 J2000 处就有
−0.24″ 的系统差（见本目录同批次的提交说明）。

截断阈值（单位分别是 rad / rad / AU）与实测误差：

    系列   阈值      项数    相对未截断的 VSOP87D，1526-2526 最大
    L      1e-9      818     0.0025″
    B      1e-8       65     FK5 改正里 tan β 的影响 ~6e-9″（可忽略）
    R      1e-9      570     光行差 0.0015″；日地距离 2.8 km

L 取 1e-9 的理由：这样截断误差 0.0025″ 与本实现的章动误差（0.0029″）同量级，
截断就不再是短板；再往下压（3e-10 是 0.00017″，但要多 210 项）已经轮不到它
决定总误差——比它大得多的是 VSOP87 本身相对 VSOP2000/DE440 的 ~0.015″。

B 之所以可以粗：地球日心黄纬最大不过 ~1e-4 rad，它只经由 FK5 改正里的
`0.03916·(cos λ' + sin λ')·tan β` 进入黄经，整项本身只有 5e-6″ 量级。

R 之所以必须细：周年光行差 −20.49″/R 对 R 是敏感的，R 只留到 1e-8 AU
（213 项）时光行差就差 0.012″——已经与章动同级。

Run:  python tools/gen_vsop87.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, os.pardir)
SRC = os.path.join(ROOT, 'third_party', 'vsop87', 'VSOP87D.ear')
OUT = os.path.join(ROOT, 'crates', 'ephemeris', 'src', 'vsop87_tables.rs')

# 变量号 -> (Rust 前缀, 截断阈值)
VARS = {1: ('L', 1e-9), 2: ('B', 1e-8), 3: ('R', 1e-9)}

HEADER = '''// @generated by tools/gen_vsop87.py -- do not edit by hand.
//
// VSOP87D 地球日心黄道坐标，参考**当日动力学平黄道分点**。原始系数，
// 不是 Meeus 附录 III 的转抄版（那一份 L0 只留 64/559 项，J2000 处就差 −0.24″）。
//
// 每项为 A·cos(B + C·τ)，τ 为儒略千年数（J2000 起算，故 τ = (JDE−2451545)/365250）。
// L、B 单位弧度，R 单位 AU。
//
// 截断阈值与误差见 tools/gen_vsop87.py 的文档字符串。
'''


def parse(path):
    """→ {(变量号, 幂次): [(A, B, C), ...]}"""
    series = {}
    cur = None
    with open(path, encoding='latin-1') as f:
        for line in f:
            if 'VSOP87 VERSION D' in line:
                var = int(re.search(r'VARIABLE (\d)', line).group(1))
                k = int(re.search(r'\*T\*\*(\d)', line).group(1))
                cur = (var, k)
                series[cur] = []
                continue
            p = line.split()
            # 记录行 = 版本码 + 序号 + 12 个整数乘子 + S,K,A,B,C
            if cur is None or len(p) < 17:
                continue
            _s, _k, a, b, c = (float(x) for x in p[-5:])
            series[cur].append((a, b, c))
    return series


def main():
    series = parse(SRC)
    parts = [HEADER]
    for var, (prefix, thr) in sorted(VARS.items()):
        names = []
        for k in sorted(k for (v, k) in series if v == var):
            kept = [t for t in series[(var, k)] if t[0] >= thr]
            name = f'EARTH_{prefix}{k}'
            names.append(name)
            parts.append(f'pub(crate) static {name}: &[(f64, f64, f64)] = &[')
            for a, b, c in kept:
                parts.append(f'    ({a!r}, {b!r}, {c!r}),')
            parts.append('];')
        # 幂次表：让 sun.rs 循环而不是把 6 个和式手写出来
        parts.append(f'pub(crate) static EARTH_{prefix}: &[&[(f64, f64, f64)]] = &[')
        parts.append('    ' + ', '.join(names) + ',')
        parts.append('];')
        tot = sum(1 for k in series if k[0] == var for t in series[k] if t[0] >= thr)
        print(f'  {prefix}: {len(names)} 个幂次，共 {tot} 项（阈值 {thr:g}）')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(parts) + '\n')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
