#!/usr/bin/env python3
"""从 ELP2000-82B 系数生成 crates/ephemeris/src/elp2000_tables.rs。

系数来源：`third_party/elp2000-82b/ELP2000-82b.json`（MIT，见该目录 README）。
该 JSON 是**已截断**的 ELP2000-82B：作者标注截断误差 0.001″ / 0.001 km，
36 张表共 3402 项。注意 ELP22-36（潮汐/月体形状/相对论/太阳偏心率）在这份
截断下**大多是空的**——它们本身只有 0.001″–0.01″ 量级，被阈值滤掉了。

三种表结构（都由 `Elp2000-82b.js` 的求和函数决定）：

    ELP01-03   主问题        (i1,i2,i3,i4)                 A + B1..B6
    ELP04-21   地球形状/行星扰动                      (i1..i5) 或 (i1..i11) + phi + A
    ELP22-36   潮汐/月体形状/相对论/太阳偏心率

**`B` 字段丢掉了**：参考实现（`Elp2000-82b.js` 的四个求和函数）只用到 `A` 与
`phi`，`B` 一次也没用。丢掉是照它的口径走；若日后发现某个表的 `B` 有用，
`tools/truthcheck.py` 会立刻看出来。

Run:  python tools/gen_elp2000.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, os.pardir)
SRC = os.path.join(ROOT, 'third_party', 'elp2000-82b', 'ELP2000-82b.json')
OUT = os.path.join(ROOT, 'crates', 'ephemeris', 'src', 'elp2000_tables.rs')

# 表号 -> 布局。'main' = ELP01-03，'plan' = ELP10-21，'np' = 其余
LAYOUT = {**{i: 'main' for i in (1, 2, 3)},
          **{i: 'plan' for i in range(10, 22)},
          **{i: 'np' for i in list(range(4, 10)) + list(range(22, 37))}}

HEADER = '''// @generated by tools/gen_elp2000.py -- do not edit by hand.
//
// ELP2000-82B 月球理论系数（Chapront-Touzé, Chapront & Francou 1985；
// 2002 年按 LLR 重定的轨道参数）。来源与许可见 third_party/elp2000-82b/README.md。
//
// 单位：主问题表（ELP01-03）的 A 对 ELP01/02 是**角秒**、对 ELP03 是 **km**；
// 其余表的 A 角秒、phi **度**。都按弧秒/度给出，换算在 moon.rs 里做。
//
// 逐张表的表是私有的，crate 里只经 moon.rs 的求和使用——所以加一张表不必改别处。
'''

TYPES = '''/// 主问题项：`A·sin(i1·D + i2·l' + i3·l + i4·F)`（ELP03 换成 `cos`，算距离），
/// A 按拟合改正调整过（见 moon.rs）。
pub(crate) type ElpMainTerm = (i8, i8, i8, i8, f64, f64, f64, f64, f64, f64, f64);

/// 非行星扰动项：`A·sin(i1·ζ + i2·D + i3·l' + i4·l + i5·F + φ)`（φ 为度）。
///
/// 潮汐/月体形状/相对论几组（ELP22-36）不用 ζ，调用时把 ζ 传 0。
pub(crate) type ElpTerm = (i8, i8, i8, i8, i8, f64, f64);

/// 行星扰动项：前 8 个乘子作用于 8 颗行星的平黄经，后面的视表而定（见 moon.rs）。
pub(crate) type ElpPlanetaryTerm =
    (i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, i8, f64, f64);
'''


def fmt_main(r):
    return ('    ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}),'
            .format(r['i1'], r['i2'], r['i3'], r['i4'], float(r['A']),
                    float(r['B1']), float(r['B2']), float(r['B3']),
                    float(r['B4']), float(r['B5']), float(r['B6'])))


def fmt_np(r):
    return ('    ({}, {}, {}, {}, {}, {}, {}),'
            .format(r['i1'], r['i2'], r['i3'], r['i4'], r['i5'], float(r['phi']), float(r['A'])))


def fmt_plan(r):
    ints = ', '.join(str(r['i%d' % k]) for k in range(1, 12))
    return '    ({} , {}, {}),'.format(ints, float(r['phi']), float(r['A']))


def main():
    d = json.load(open(SRC, encoding='utf-8'))
    parts = [HEADER, TYPES]

    # 引数多项式与行星平黄经（资料，不是逻辑）
    parts.append('''/// W1、W2、W3、T、ϖ′ 的多项式系数（4 次，自变量为儒略世纪 T）。
/// 已按 Chapront, Chapront-Touzé & Francou (2002, A&A) 用 LLR 重定的参数改正。
pub(crate) static ELP_ARG_POLY: [[f64; 5]; 5] = [
    [785939.8782, 1732559343.3328, -6.870, 0.006604, -0.00003169],
    [300071.6518, 14643420.3304, -38.2639, -0.045047, 0.00021301],
    [450160.3265, -6967919.8851, 6.3593, 0.007625, -0.00003586],
    [361679.1880, 129597742.3016, -0.0202, 0.000009, 0.00000015],
    [370574.4136, 1161.2283, 0.5327, -0.000138, 0.0],
];

/// 八颗行星的平黄经：`P0 + P1·T`，取自 VSOP82 的表 F。
pub(crate) static ELP_PLANET_POLY: [[f64; 2]; 8] = [
    [908103.25986, 538101628.68898],
    [655127.28305, 210664136.43355],
    [361679.22059, 129597742.2758],
    [1279559.78866, 68905077.59284],
    [123665.34212, 10925660.42861],
    [180278.89694, 4399609.65932],
    [1130598.01841, 1542481.19393],
    [1095655.19575, 786550.32074],
];

/// 拟合到 DE200/LE200 的改正量，单位角秒（deltanu / deltanp 还要除以 W1 的一次项）。
pub(crate) const ELP_DELTANU_ARCSEC: f64 = 0.55604;
pub(crate) const ELP_DELTAE_ARCSEC: f64 = 0.01789;
pub(crate) const ELP_DELTAGAMMA_ARCSEC: f64 = -0.08066;
pub(crate) const ELP_DELTANP_ARCSEC: f64 = -0.06424;
pub(crate) const ELP_DELTAEP_ARCSEC: f64 = -0.12879;
/// 地月质量比相关的两个量（ELP2000 第 7 节）。
pub(crate) const ELP_AM: f64 = 0.074801329518;
pub(crate) const ELP_DTASM: f64 = 2.0 * 0.002571881335 / (3.0 * 0.074801329518);
/// 2002 年 LLR 定出的岁差值，用在 ζ 里。
pub(crate) const ELP_PRECESSION_CONSTANT: f64 = 5029.0966 - 0.0316;''')

    NL = chr(10)   # 生成文件里的换行；用 chr(10) 免得与 shell/编辑器转义打架
    total, empty = 0, []
    for i in range(1, 37):
        key = 'ELP%02d' % i
        rows = d[key]
        fmt = {'main': fmt_main, 'np': fmt_np, 'plan': fmt_plan}[LAYOUT[i]]
        ty = {'main': 'ElpMainTerm', 'np': 'ElpTerm', 'plan': 'ElpPlanetaryTerm'}[LAYOUT[i]]
        # 空的表也产出（`&[]`）：这样 moon.rs 的求和能与参考实现逐行对应，
        # 日后重新生成时某张表从空变非空也不会悄悄漏掉。
        if rows:
            body = NL.join(fmt(r) for r in rows)   # 一项一行，与其它生成表一致
            parts.append(f'pub(crate) static {key}: &[{ty}] = &[{NL}{body}{NL}];')
        else:
            parts.append(f'pub(crate) static {key}: &[{ty}] = &[];')
            empty.append(key)
        total += len(rows)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n\n'.join(parts) + '\n')
    print(f'  36 张表共 {total} 项；其中空表 {len(empty)} 张：{", ".join(empty)}')
    print(f'  截断标注：{d["truncationArcSeconds"]}" / {d["truncationKilometers"]} km')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
