#!/usr/bin/env python3
"""生成 `docs/accuracy.md` —— **精度数字的唯一来源**。

## 为什么要有这个

同一组精度数字本来手抄在四处（README、docs/plan.md、docs/compliance.md、
crates/ephemeris/src/lib.rs），每次精度一变就要改四处，而没有任何机器检查会
提示漏了哪处。实测已经漂过好几次，其中 `lib.rs` 的"精度（必读）"一节整整
落后一个第 7 步（写着自己的误差比实际大 200 倍）。这个项目和"文档里的数字"之间
一直是这种关系：**手抄的数字必然漂移**。

所以改成：数字只由本脚本写进 `docs/accuracy.md`，其余三处**引用**它
（Rust 侧用 `#![doc = include_str!(...)]`，markdown 侧放链接）。

## 需要什么

`kernels/de421.bsp`（不进版本库，取法见 `tools/truthcheck.py` 头部）。
本脚本复用两个验收工具的计算部分（它们的 `measure()`），只负责排版。

用法:  python tools/gen_accuracy.py
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, os.pardir)
OUT = os.path.join(ROOT, 'docs', 'accuracy.md')
sys.path.insert(0, HERE)

import eclipsecheck  # noqa: E402
import spec_check  # noqa: E402
import truthcheck  # noqa: E402


def main():
    t = truthcheck.measure()
    s = spec_check.measure()
    ec = eclipsecheck.measure()
    if t is None or s is None or ec is None:
        print('缺少 kernels/de421.bsp —— 无法生成。取法见 tools/truthcheck.py 头部。')
        return 1

    lo, hi = t['kernel_span']
    rows = [
        ('太阳几何黄经', 'sun_geom', 4, '"'),
        ('太阳视黄经', 'sun_app', 4, '"'),
        ('日地距离', 'sun_dist', 2, ' km'),
        ('月球黄经', 'moon_lon', 4, '"'),
        ('月球黄纬', 'moon_lat', 4, '"'),
        ('月地距离', 'moon_dist', 3, ' km'),
    ]
    pos = '\n'.join(
        f'| {name} | {t[k][0]:+.{dp}f}{u} | {t[k][1]:.{dp}f}{u} | {t[k][2]:.{dp}f}{u} |'
        for name, k, dp, u in rows)

    bm = t['builtin_moon']
    spec = '\n'.join(
        f'| {name} | {n} | {s[k][1]:.3f} s | **{s[k][2]:.3f} s** |'
        for name, k, n in [('朔', 'new_moon', s['n_new_moon']),
                           ('节气', 'term', s['n_term'])])

    # 机器可读的"被引用的数字"清单，供 tools/doccheck.py 校验别处的引用。
    # 放在文件末尾的注释里，解析简单，且与人读的表格同源（都由上面的 measure 来）。
    tracked = chr(10).join([
        f'sun_app_med_abs={t["sun_app"][1]:.4f}',
        f'moon_lon_med_abs={t["moon_lon"][1]:.4f}',
        f'moon_lon_max={t["moon_lon"][2]:.4f}',
        f'moon_dist_med_abs={t["moon_dist"][1]:.3f}',
        f'sun_dist_med_abs={t["sun_dist"][1]:.2f}',
        f'spec_new_moon_max={s["new_moon"][2]:.3f}',
        f'spec_term_max={s["term"][2]:.3f}',
        f'builtin_moon_med_abs={bm[0]:.3f}',
        f'eclipse_solar_missing={ec["solar"]["missing"]}',
        f'eclipse_solar_wrong={ec["solar"]["wrong"]}',
        f'eclipse_lunar_missing={ec["lunar"]["missing"]}',
        f'eclipse_lunar_wrong={ec["lunar"]["wrong"]}',
    ])

    text = f'''<!-- @generated by tools/gen_accuracy.py -- do not edit by hand. -->

# 精度

**本文件是精度数字的唯一来源。** 别处的数字都引用这里，不要手抄。

真值不是 ERFA/astropy 的**模型**，而是 **JPL `{t["kernel"]}`**（覆盖 1900–2053 年，
JD {lo:.1f} – {hi:.1f}）。
理由：astropy builtin 的月球对同一真值是**中位\\|差\\| {bm[0]:.3f}″、最大 {bm[1]:.3f}″**，
而本实现是 {t['moon_lon'][1]:.4f}″ —— 拿它当参照量不出我们的精度。

## 位置（{t["n"]} 个时刻，1900–2050）

| 量 | 中位 | 中位\\|差\\| | 最大\\|差\\| |
|---|---|---|---|
{pos}

"太阳几何黄经"是**主指标**：两边同口径、不含光行差与章动，所以验收不依赖
我们自己的任何模型。"太阳视黄经"要在真值侧补光行差与章动，等于复刻了
`sun.rs` 的口径，只能当辅助。

## GB/T 33661-2017 §5.2：朔和节气的北京时间精度应达到 1 s

| | 事件数 | 中位\\|偏差\\| | 最大\\|偏差\\| |
|---|---|---|---|
{spec}

两侧用**同一套 ΔT**，所以量到的是模型/理论的误差——正是 §5.2 所指
（ΔT 自身的不确定度见 `README.md` 的"适用范围"一节）。判据 ≤1 s，均已达标。

## 日月食（对 NASA《五千年日月食目录》，1901–2100）

| | 目录 | 配对 | 漏 | 类型不符 |
|---|---|---|---|---|
| 日食（中心食/偏食） | {ec["solar"]["catalog"]} | {ec["solar"]["matched"]} | {ec["solar"]["missing"]} | {ec["solar"]["wrong"]} |
| 月食（半影/偏/全） | {ec["lunar"]["catalog"]} | {ec["lunar"]["matched"]} | {ec["lunar"]["missing"]} | {ec["lunar"]["wrong"]} |

日食的**日期全中**（多出的两次是 1900 年，在目录范围之外）。所有类型差异都是
同一类原因：本实现用的是**纯几何**的本影/半影，没有按地球大气把它放大 ~2%
（Danjon）——那正好是"擦边"那几次的偏/全/半影分类翻转。要不要补那个经验改正
是个取舍，见 `crates/ephemeris/src/eclipse.rs` 与 `third_party/eclipse-catalog/README.md`。

## 复现

```bash
python tools/truthcheck.py    # 位置（对 JPL 真值）
python tools/spec_check.py    # §5.2 的 1 s 判据
python tools/eclipsecheck.py  # 日月食（对 NASA 食典）
python tools/gen_accuracy.py  # 重新生成本文件
```

需要 `kernels/de421.bsp`（不进版本库，取法见 `tools/truthcheck.py` 头部）。
1900–2053 之外未经真值验证——那边是理论外推，日界由 ΔT 的不确定度主导。

<!-- tracked-claims
{tracked}
-->
'''
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print(f'wrote {OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
